### ISSUE TITLE
transparancy

### ISSUE THREAD

**Issue by addekung** [satoru8/FullTransparency#1]
it just isn't transparent at all?? D:

**Comment by coolcalcacol** [comment]
You need to toggle the transparency option in better discord's settings then restart discord, then it should work fine.

**Comment by coolcalcacol** [comment]
"A theme designed specifically for using the transparency option in BetterDiscord, with extra features/animations. Use together with FullTransparency plugin. (Not required) *Fully close discord and reopen when first turning on transparency option. Ctrl + R does not work."

You can join the discord for faster support, in the \#support channel: http://discord.gg/fjvwb95

**Comment by satoru8** [comment]
Learn to read first. Not an issue. Theme works fine.
